<?php

namespace Foundation\Requests\KYC;

use Illuminate\Foundation\Http\FormRequest;

class StoreRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'first_name' => 'required|string',
            'last_name' => 'required|string',
            'email' => 'required|email',
            'phone' => 'required',
            'dob' => 'required|date',
            'document_number' => 'required',
            'permanent_country' => 'required',
            'permanent_city' => 'required',
            'permanent_street_address' => 'required',
            'permanent_postal_code' => 'required',
            'current_country' => 'required',
            'current_city' => 'required',
            'current_street_address' => 'required',
            'current_postal_code' => 'required',
            'occupation' => 'nullable|string',
            'father_name' => 'nullable|string' ,
            'grandfather_name' => 'nullable|string',
            'company_name' => 'nullable|string',
            'company_location' => 'nullable|string',
            'pan_vat_number' => 'nullable|string',

            'document.front' => 'required|mimes:jpg,jpeg,png,svg',
            'document.back' => 'required|mimes:jpg,jpeg,png,svg'
        ];
    }

    /**
     * Get custom messages for validator errors.
     *
     * @return array
     */
    public function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
