<?php

namespace Foundation\Requests\Post;

use Foundation\Lib\PostType;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class StoreRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'title' => 'required|max:200|string',
            'slug' => 'required|max:200|string|unique:posts,slug',
            'image' => 'sometimes|nullable|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            'post_type' => 'required|in:' . implode(',', array_keys(PostType::$current)),
            'content' => 'sometimes|nullable|min:10',
            'category' => 'required_if:post_type,' . PostType::POST_TYPE_SUPPORT .'|nullable|exists:categories,id',
            'tags' => 'sometimes|nullable|array',
            'seo_title' => 'sometimes|nullable|max:150|string',
            'seo_slug' => 'sometimes|nullable|max:150|unique:posts,seo_slug',
            'seo_keywords' => 'sometimes|nullable|max:150|string',
            'seo_desc' => 'sometimes|nullable|max:150|string',
            'status' => 'required|boolean',
        ];
    }

    /**
     * Get custom messages for validator errors.
     *
     * @return array
     */
    public function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
