<?php

namespace Foundation\Requests\Bank;

use Illuminate\Foundation\Http\FormRequest;

class StoreRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'name'            => 'required|max:200|string|unique:banks,name',
            'branch'          => 'required|max:200',
            'account_name'    => 'required|max:200',
            'account_number'  => 'required|max:200',
            'currency'        => 'required|max:200',
            'description'     => 'sometimes|nullable|max:200',
            'status'          => 'required|boolean',
        ];
    }

    /**
     * Get custom messages for validator errors.
     *
     * @return array
     */
    public function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
